### ISSUE TITLE
安卓应用闪退

### ISSUE THREAD

**Issue by swieer** [e3m-software/bluetooth_x_print#2]
I/BluetoothAdapter( 2270): getBluetoothLeScanner
I/hwaps   ( 2270): JNI_OnLoad
W/BluetoothAdapter( 2270): getBluetoothService() called with no BluetoothManagerCallback
I/flutter ( 2270): cur device status: 1
E/AndroidRuntime( 2270): FATAL EXCEPTION: main
E/AndroidRuntime( 2270): Process: com.example.bluetooth_print_example, PID: 2270
E/AndroidRuntime( 2270): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 2270): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:430)
E/AndroidRuntime( 2270): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:272)
E/AndroidRuntime( 2270): 	at com.example.bluetooth_x_print.BluetoothPrintPlugin$4.OnFailed(BluetoothPrintPlugin.java:362)
E/AndroidRuntime( 2270): 	at net.posprinter.asynncTask.PosAsynncTask.onPostExecute(PosAsynncTask.java:34)
E/AndroidRuntime( 2270): 	at net.posprinter.asynncTask.PosAsynncTask.onPostExecute(PosAsynncTask.java:13)
E/AndroidRuntime( 2270): 	at android.os.AsyncTask.finish(AsyncTask.java:692)
E/AndroidRuntime( 2270): 	at android.os.AsyncTask.-wrap1(AsyncTask.java)
E/AndroidRuntime( 2270): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:709)
E/AndroidRuntime( 2270): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime( 2270): 	at android.os.Looper.loop(Looper.java:156)
E/AndroidRuntime( 2270): 	at android.app.ActivityThread.main(ActivityThread.java:6595)
E/AndroidRuntime( 2270): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2270): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
E/AndroidRuntime( 2270): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
I/Process ( 2270): Sending signal. PID: 2270 SIG: 9
Lost connection to device.

**Comment by swieer** [comment]
myBinder.ConnectBtPort(address, new TaskCallback() {
        @Override
        public void OnSucceed() {
          IS_CONNECT = true;
        }

        @Override
        public void OnFailed() {
          IS_CONNECT = false;
          result.error("OnFailed", "Cannot connect Device", null);
        }
      });

      result.success(true);
应该是这个result.success(true)的位置不对

**Comment by swieer** [comment]
安卓应用连接蓝牙总是失败，是什么呢，我不太会安卓，比较难搞
