### ISSUE TITLE
enter PIN number at the first pairing, “0000” 

### ISSUE THREAD

**Issue by abdulrojakdev** [e3m-software/bluetooth_x_print#4]
[log] cur device status: 1
D/AndroidRuntime(27102): Shutting down VM
E/AndroidRuntime(27102): FATAL EXCEPTION: main
E/AndroidRuntime(27102): Process: com.tes.debug, PID: 27102
E/AndroidRuntime(27102): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(27102): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
E/AndroidRuntime(27102): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:268)
E/AndroidRuntime(27102): 	at com.example.bluetooth_x_print.BluetoothPrintPlugin$4.OnFailed(BluetoothPrintPlugin.java:361)
E/AndroidRuntime(27102): 	at net.posprinter.asynncTask.PosAsynncTask.onPostExecute(PosAsynncTask.java:34)
E/AndroidRuntime(27102): 	at net.posprinter.asynncTask.PosAsynncTask.onPostExecute(PosAsynncTask.java:13)
E/AndroidRuntime(27102): 	at android.os.AsyncTask.finish(AsyncTask.java:695)
E/AndroidRuntime(27102): 	at android.os.AsyncTask.access$600(AsyncTask.java:180)
E/AndroidRuntime(27102): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
E/AndroidRuntime(27102): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(27102): 	at android.os.Looper.loop(Looper.java:201)
E/AndroidRuntime(27102): 	at android.app.ActivityThread.main(ActivityThread.java:6810)
E/AndroidRuntime(27102): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27102): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AndroidRuntime(27102): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
I/Process (27102): Sending signal. PID: 27102 SIG: 9

**Comment by biloo-dev** [comment]
i had same issue @abdulrojakdev do you fix this problem ??

**Comment by abdulrojakdev** [comment]
> i had same issue @abdulrojakdev do you fix this problem ??

I haven't found the solution yet

**Comment by biloo-dev** [comment]
hi @abdulrojakdev !! you can try this package, it supports pin code connection 

This package contains an example or a test you can use 
[https://pub.dev/packages/flutter_bluetooth_serial](url)

Additionally, this package allows you to format your concept data in any way you want 
[esc_pos_utils_plus: ^2.0.2](url)
